server:
  port: 9002
  servlet:
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      min-spare: 30
    #tomcat连接超时时间
    connection-timeout: 6000
#  ssl:
#    key-store: classpath:certificate/tomcat.pkcs12
#    key-store-password: 111111
#    key-store-type: PKCS12
#    #key-alias: maike
#    #enabled: true
spring:
  application:
    name: GeekPlusAdmin
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      username: root
      password: 111111
      url: jdbc:mysql://localhost:3306/admin?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      max-evictable-idle-time-millis: 900000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: on
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: on
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      useGlobalDataSourceStat: on
      defaultAutoCommit: on # 事物自动提交
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  devtools:
    restart:
      enabled: on  #设置开启热部署
      additional-paths: src/main/java #重启目录
  freemarker:
    check-template-location: false
  #redis配置
  redis:
    #redis服务地址 端口 密码
    host: 127.0.0.1
    port: 6379
    password: 111111
    #Redis数据库索引（默认为0）
    #database: 0
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 80
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 30
        #连接池中的最小空闲连接
        min-idle: 5
    #连接超时时间（毫秒）
    timeout: 9000
  mail:
    username: GeekPlus
mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  type-aliases-package: com.geekplus.webapp.**.entity
  configuration:
    cache-enabled: on
    use-generated-keys: on
    default-executor-type: reuse
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#Swagger配置
swagger:
  enable: true
  pathMapping: /prod-api
#security:
#  basic:
#    enable: false
#    username: geekplus
#    password: 123456cjj
#pagehelper分页插件配置
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
token:
  expireTime: 1800
  header: Plus-Token
  secret: webwebbvjkbvkjbdkjvbkjbvkjbdxckj
geekplus:
  name: GeekPlus
  version: 1.0.0
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  #文件路径 示例（ Windows配置D:/appName/uploadPath，Linux配置 /home/appName/uploadPath）
  profile: /home/appName/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
